packages:
  - packages/**
  - playgrounds/**

catalog:
  '@antfu/eslint-config': ^4.12.0
  '@antfu/ni': ^24.3.0
  '@nuxt/module-builder': ^1.0.1
  '@types/node': ^22.14.1
  bumpp: ^10.1.0
  eslint: ^9.24.0
  nuxt: 3.16.2
  pathe: ^2.0.3
  taze: ^19.0.2
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unimport: ^5.0.0
  unplugin-auto-import: ^19.1.2
  unplugin-vue-components: ^28.4.1
  upath: ^2.0.1
  vite: 6.2.2
  vue-tsc: ^2.2.8
  vuetify: ^3.8.1
