packages:
  - packages/**
  - playgrounds/**

catalog:
  '@antfu/eslint-config': ^4.12.0
  '@antfu/ni': ^24.3.0
  '@arethetypeswrong/cli': ^0.17.4
  '@mdi/font': 7.4.47
  '@nuxt/fonts': ^0.11.1
  '@nuxt/module-builder': ^1.0.1
  '@nuxt/schema': ^3.16.2
  '@nuxtjs/i18n': ^9.5.4
  '@tsconfig/node22': ^22.0.0
  '@types/node': ^22.14.1
  '@vitejs/plugin-vue': ^5.2.3
  '@vue/tsconfig': ^0.7.0
  bumpp: ^10.1.0
  eslint: ^9.24.0
  nuxt: 3.17.1
  pathe: ^2.0.3
  read-yaml-file: ^2.1.0
  sass-embedded: ^1.86.3
  taze: ^19.0.2
  tsx: ^4.19.3
  typescript: ~5.8.3
  unbuild: ^3.5.0
  unimport: ^5.0.1
  unplugin-auto-import: ^19.1.2
  unplugin-fonts: ^1.3.1
  unplugin-vue-components: ^28.4.1
  upath: ^2.0.1
  vite: 6.2.6
  vite-plugin-inspect: ^11.0.0
  vue: ^3.5.13
  vue-tsc: ^2.2.8
  vuetify: ^3.8.1
