packages:
  - packages/**
  - playgrounds/**
  - '!playgrounds/nuxt-i18n-v8'

patchedDependencies:
  unimport@4.2.0: patches/unimport@4.2.0.patch
  unimport@5.0.0: patches/unimport@5.0.0.patch

catalog:
  '@antfu/eslint-config': ^4.12.0
  '@antfu/ni': ^24.3.0
  '@arethetypeswrong/cli': ^0.17.4
  '@mdi/font': 7.4.47
  '@nuxt/fonts': ^0.11.1
  '@nuxt/kit': 3.17.1
  '@nuxt/module-builder': ^1.0.1
  '@nuxt/schema': 3.17.1
  '@tsconfig/node22': ^22.0.0
  '@types/node': ^22.14.1
  '@vitejs/plugin-vue': ^5.2.3
  '@vue/tsconfig': ^0.7.0
  bumpp: ^10.1.0
  eslint: ^9.24.0
  nuxt: 3.17.1
  pathe: ^2.0.3
  read-yaml-file: ^2.1.0
  sass-embedded: ^1.86.3
  taze: ^19.0.2
  tsx: ^4.19.3
  typescript: ~5.8.3
  unbuild: ^3.5.0
  unhead: 2.0.8
  unimport: ^5.0.0
  unplugin-auto-import: ^19.1.2
  unplugin-fonts: ^1.3.1
  unplugin-vue-components: ^28.4.1
  upath: ^2.0.1
  vite: 6.2.6
  vite-plugin-inspect: ^11.0.0
  vue: ^3.5.13
  vue-tsc: ^2.2.8
  vuetify: ^3.8.3

catalogs:
  i18n-v10:
    '@intlify/unplugin-vue-i18n': 6.0.5
    '@nuxt/kit': 3.17.1
    '@nuxt/schema': 3.17.1
    '@nuxtjs/i18n': ^10.0.0-beta.2
    nuxt: 3.17.1
    unhead: 2.0.8
  i18n-v9:
    '@intlify/unplugin-vue-i18n': 6.0.5
    '@nuxt/kit': 3.17.1
    '@nuxt/schema': 3.17.1
    '@nuxtjs/i18n': 9.5.3
    nuxt: 3.17.1
    unhead: 2.0.8
