/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    VuetifyApp: typeof import('vuetify/components/VApp')['VApp']
    VuetifyBtn: typeof import('vuetify/components/VBtn')['VBtn']
    VuetifyCard: typeof import('vuetify/components/VCard')['VCard']
    VuetifyCol: typeof import('vuetify/components/VGrid')['VCol']
    VuetifyContainer: typeof import('vuetify/components/VGrid')['VContainer']
    VuetifyImg: typeof import('vuetify/components/VImg')['VImg']
    VuetifyMain: typeof import('vuetify/components/VMain')['VMain']
    VuetifyRow: typeof import('vuetify/components/VGrid')['VRow']
  }
  export interface ComponentCustomProperties {
    VuetifyClickOutside: typeof import('vuetify/directives')['ClickOutside']
  }
}
